-- Table: DONOR
CREATE TABLE DONOR (
    Did INT PRIMARY KEY,
    Dname VARCHAR(255),
    DOB DATE,
    DContactNo VARCHAR(15),
    Rid INT,
    FOREIGN KEY (Rid) REFERENCES RECEPTIONIST(Rid)
);

-- Table: HOSPITAL
CREATE TABLE HOSPITAL (
    Hid INT PRIMARY KEY,
    Hname VARCHAR(255),
    HContactNo VARCHAR(15)
);

-- Table: PATIENT
CREATE TABLE PATIENT (
    Pid INT PRIMARY KEY,
    Pname VARCHAR(255),
    PContactNo VARCHAR(15),
    Hid INT,
    FOREIGN KEY (Hid) REFERENCES HOSPITAL(Hid)
);

-- Table: BLOOD
CREATE TABLE BLOOD (
    Bid INT PRIMARY KEY,
    Blood_bank_ID INT,
    Blood_type VARCHAR(10),
    Cost DECIMAL(10, 2),
    Did INT,
    Tid INT,
    FOREIGN KEY (Blood_bank_ID) REFERENCES BLOOD_BANK(Blood_bank_ID),
    FOREIGN KEY (Did) REFERENCES DONOR(Did),
    FOREIGN KEY (Tid) REFERENCES LAB_TECHNICIAN(Tid)
);

-- Table: BLOOD_BANK
CREATE TABLE BLOOD_BANK (
    Blood_bank_ID INT PRIMARY KEY,
    BBname VARCHAR(255),
    Issues VARCHAR(255),
    Mid INT,
    FOREIGN KEY (Mid) REFERENCES BLOOD_BANK_MANAGER(Mid)
);

-- Table: BLOOD_BANK_MANAGER
CREATE TABLE BLOOD_BANK_MANAGER (
    Mid INT PRIMARY KEY,
    BM_Name VARCHAR(255),
    Mcontact VARCHAR(15)
);

-- Table: LAB_TECHNICIAN
CREATE TABLE LAB_TECHNICIAN (
    Tid INT PRIMARY KEY,
    Blood_bank_ID INT,
    Tech_name VARCHAR(255),
    Qualification VARCHAR(255),
    FOREIGN KEY (Blood_bank_ID) REFERENCES BLOOD_BANK(Blood_bank_ID)
);

-- Table: RECEPTIONIST
CREATE TABLE RECEPTIONIST (
    Rid INT PRIMARY KEY,
    Blood_bank_ID INT,
    RContactNo VARCHAR(15),
    Rname VARCHAR(255),
    FOREIGN KEY (Blood_bank_ID) REFERENCES BLOOD_BANK(Blood_bank_ID)
);

-- Table: HOSPITAL_LOCATION
CREATE TABLE HOSPITAL_LOCATION (
    Hid INT PRIMARY KEY,
    Haddress VARCHAR(255),
    FOREIGN KEY (Hid) REFERENCES HOSPITAL(Hid)
);

-- Table: DELIVERS
CREATE TABLE DELIVERS (
    Hid INT,
    Pid INT,
    Time DATETIME,
    Bid INT,
    PRIMARY KEY (Hid, Pid, Bid),
    FOREIGN KEY (Hid) REFERENCES HOSPITAL(Hid),
    FOREIGN KEY (Pid) REFERENCES PATIENT(Pid),
    FOREIGN KEY (Bid) REFERENCES BLOOD(Bid)
);

-- Table: ORDERS
CREATE TABLE ORDERS (
    Hid INT,
    Blood_bank_ID INT,
    Qty INT,
    Bid INT,
    PRIMARY KEY (Hid, Blood_bank_ID, Bid),
    FOREIGN KEY (Hid) REFERENCES HOSPITAL(Hid),
    FOREIGN KEY (Blood_bank_ID) REFERENCES BLOOD_BANK(Blood_bank_ID),
    FOREIGN KEY (Bid) REFERENCES BLOOD(Bid)
);

-- Table: EMPLOYED_BY
CREATE TABLE EMPLOYED_BY (
    Rid INT,
    Blood_bank_ID INT,
    PRIMARY KEY (Rid, Blood_bank_ID),
    FOREIGN KEY (Rid) REFERENCES RECEPTIONIST(Rid),
    FOREIGN KEY (Blood_bank_ID) REFERENCES BLOOD_BANK(Blood_bank_ID)
);
